### ISSUE TITLE
Create chatette-vscode readme

### ISSUE THREAD

**Issue by cendekia** [cendekia/chatette-vscode#1]
Please help to change default vscode readme into the correct on

**Comment by akdir** [comment]
I can make you a readme @cendekia if you want. Like to hear from ya ;).

**Comment by cendekia** [comment]
Yes please @akdir

**Comment by akdir** [comment]
Oh thanks for letting me ;), I will try my best @cendekia. Had to first research about Chatette and Rasa, because I have not used it before. Looks like a very cool and fun projects, will maybe try to create my own Chatbot someday using Chatette and VSCode, so your extension would be very helpful.

**Comment by cendekia** [comment]
> Oh thanks for letting me ;), I will try my best @cendekia. Had to first research about Chatette and Rasa, because I have not used it before. Looks like a very cool and fun projects, will maybe try to create my own Chatbot someday using Chatette and VSCode, so your extension would be very helpful.

Yep you should try Rasa @akdir. It's easy to use based on my experience so far :)

**Comment by akdir** [comment]
I created a new README.md and changed the CHANGELOG.md a bit @cendekia.

Also I have added 3 preview images to show people on the README how your extension looks like with syntax highlighting. I used Polacode VSCode Extension to take the code screenshot. 
I added 3 preview images, because I would like to show you 3 different themes. The default visual Studio theme in my opinion does not color the syntax very good and pretty, it is to saturated. I still created a screenshot with the default VSCode dark theme. I also used my own Theme(Super One Dark), which I really like. It is the same as One Dark, but with a dark background. The last preview is the normal Onedark theme that is used in the Atom Code Editor. 

Now you can choose which you like. If you don't like all 3 of them, I would like to hear which theme you do like to use.

If there are any criticism on the README.md file or CHANGELOG.md file, I would like to hear it! 

Thanks for the opportunity ;), and I hope you can develop this extension even further and make it even better!
